### ISSUE TITLE
Can't locate any elements with ByNearestWidget

### ISSUE THREAD

**Issue by PeterWippermann** [niloc132/gxt-driver#10]
I'm trying to get the GWT and GXT Webdrivers running. But no matter what element I'm trying to find, I always get a NoSuchElementException. In contrast to this, my "native Selenium" finders succeed.

Even the following (fail-safe?) example will fail. While the first two lines execute successfully, the last line gets an exception.

```
        WebElement findElement = driver.findElement(By.id(USERNAME_INPUT));
        findElement.sendKeys(userName);

        Field find = GwtWidget.find(Field.class, driver, findElement).done();
```

I traced the error and found out that the "ExportedMethods" that are executed remotely in the browser, don't return any elements. E.g. one result set was `{success, false}`

Now I don't know what do to. Is there anything missing in the client-side code? I have inherited these modules:

```
    <inherits name="org.senchalabs.gwt.gwtdriver.GwtDriver"/>
    <inherits name="org.senchalabs.gwt.gwtdriver.gxt.TestableGXT" />
```

**Comment by niloc132** [comment]
Without more details (what GXT Field widget, how was it created/attached, and are you certain that USERNAME_INPUT is set on the root element of that widget?), it is hard to be sure about much. Can you confirm that the example project works locally? Can you modify that example to fail in the same way?

Make sure that `findElement` actually is a widget - my best guess is that it isn't, or that some setup didn't work right. The fact that you got `{success, false}` back means at least that some GWT-Driver client code is listening, but is there any chance that there is more than one GWT module?

**Comment by PeterWippermann** [comment]
I also debugged the code that is trying to find the client modules. It only finds one module and sets it as the default module.

**Comment by branflake2267** [comment]
Colin's right. Usually it's the module isn't getting compiled in with the project. Could you provide a small test case project to run locally?

**Comment by branflake2267** [comment]
Just in case, we've got some more examples here too: http://docs.sencha.com/gxt/3.x/testing/integration_testing/gxt-driver/Examples.html

**Comment by PeterWippermann** [comment]
This is how the view with the USERNAME_INPUT is constructed:

```
import com.sencha.gxt.widget.core.client.form.TextField;
...
protected TextField userName;
...
        KeyDownHandler keyHandler = new KeyDownHandler() {
            @Override
            public void onKeyDown(KeyDownEvent event) {
                if (KeyCodes.KEY_ENTER == event.getNativeEvent().getKeyCode()) {
                    event.stopPropagation();
                    onSubmit();
                }
            }
        };

        userName = new TextField();
        FieldLabel userNameFieldLabel = new FieldLabel(userName, DMessages.DMESSAGES.loginDialog_username());
        userName.setId(ID_USERNAME);
        userName.addKeyDownHandler(keyHandler);
        loginContainer.add(userNameFieldLabel, new VerticalLayoutData(.95, -1));
```

**Comment by PeterWippermann** [comment]
I will try to run your example project next and let you know :-)

**Comment by branflake2267** [comment]
Looks fine. What I would want to know is 1. is the TestableGXT compiled into the project, this is usually the cause of the issue of not finding widgets. 2. Have you found any widgets in the project or is this the first time you've tried it? I suspect try something super simple first (which you are I think.), but check the module compile.

**Comment by niloc132** [comment]
Okay, right sorts of steps to rule out these possibilities, though I do find it slightly odd that you can `WebElement.sendKeys` to the widget's root (a `div`, not the `input` itself) and have that behave. 

The purpose of ByNearestWidget is to start from a dom element and work your way up the tree until a class is found that is an instance of the type provided. If ByNearestWidget is broken and can only find from a child element, you could modify your findElement to find the first `input` inside the element with that ID.

One other idea - any chance that you are compiling with class metadata disabled? I don't believe we have a check that class names are sane, but if they are not, the ByWidget and ByNearestWidget won't work.

@branflake2267 he said he has the inherits, and pointed out that the module is talking back correctly, and the reply from the instanceOf check is sane, just not the value we want (`{success, false}`), so yes, those steps are right.

**Comment by PeterWippermann** [comment]
@niloc132 You're right. It's indeed strange that I can `sendKeys()` to a `div`!
I took a look at the HTML and noticed, that the div[@id='username'] and the nested input[@id='username-input']. I was wondering where this came from and found this to be Sencha's GXT "magic":

```
  public FieldLabel(Widget widget, FieldLabelAppearance appearance) {
    super(true);
    this.appearance = appearance;
    String id;
    if (widget == null) {
      id = null;
    } else {
      id = ComponentHelper.getWidgetId(widget);

      if (widget instanceof ValueBaseField<?>) {
        id += "-input";
      }
    }
...
```

I will correct my test and see how things change.

**Comment by PeterWippermann** [comment]
One intermediate question @branflake2267 : How can I double check that the module get's integrated in my GWT compile output?
Standard logs from the maven-mojo are spare and the created code is obfuscated, you know. At least I didn't find anything.

**Comment by branflake2267** [comment]
Compiler metrics can be added for more information on compile. If field doesnt work, I know finding a text button has worked for me. What I do is setup a simple entry point with only one widget and see if I can find that with the driver. Once I know that works, I then start making fancier finds on my views. Just a thought.

**Comment by niloc132** [comment]
The fact that you are getting responses at all from the client modules indicates that it is set up correctly - it found the module, and found the selenium exporter wiring, and successfully sent/received at least one message (i.e. the 'success', false message).

If your experiment doesn't work, can you privately email me the `*.cache.*` compiled source so I can take a quick look for something that seems wrong?

**Comment by PeterWippermann** [comment]
Ok, I just got your sample app running. These tests also fail. In the sample app not even the default module can be determined. The response is an empty ArrayList (internal state of the response object is "success" again):

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at org.senchalabs.gwt.gwtdriver.ModuleUtilities.executeExportedFunction(ModuleUtilities.java:89)
    at org.senchalabs.gwt.gwtdriver.invoke.ClientMethodsFactory$InvocationHandlerImplementation.invoke(ClientMethodsFactory.java:61)
    at com.sun.proxy.$Proxy6.instanceofwidget(Unknown Source)
    at org.senchalabs.gwt.gwtdriver.by.ByWidget.findElements(ByWidget.java:62)
    at org.openqa.selenium.remote.RemoteWebElement.findElements(RemoteWebElement.java:164)
    at org.openqa.selenium.support.pagefactory.ByChained.findElements(ByChained.java:72)
    at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:346)
    at org.senchalabs.gwt.gwtdriver.gxt.models.Window$WindowFinder.done(Window.java:82)
    at com.sencha.gxt.mail.integration.AuthenticationTest.testLogin(AuthenticationTest.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

That's strange because when I execute the JavaScript (frames[1].$moduleName) in Firefox' debugger console by myself I can see the module name! And in my original app at least the module recognition worked?!

So could it be that Selenium's Firefox extension is not working correctly for me?

**Comment by PeterWippermann** [comment]
I also adapted my local test. Now I'm finding the TextFields div with a normal ID-Locator and do not directly access the nested input field. So the WebElement should be the right one now.

As I suspected, also with this WebElement the GWT-Driver can't construct a model from that. The error result stayed the same.

**Comment by branflake2267** [comment]
For me, updating Selenium to the latest dependencies has helped with some issues in the past. Not sure that will for you. Maybe a long shot tho.

**Comment by branflake2267** [comment]
Sounds like you might be close. Something I do to test if the compiled application running in web mode or dev mode, at a giving url is ask the web driver to first goto the url, and then set a break point. I verify that the app is loaded. Then what I do is add to it, by adding a simple content panel to the entry point. 
1. driver.getUrl(gotoUrl)
2. Next try out a container. 
   WebElement framedPanelElement = driver.findElement(new FasterByChained(By.xpath(".//*"), new ByWidget(driver,
       com.sencha.gxt.widget.core.client.ContentPanel.class)));

And break on System.out. on the next line to verify it found the element was found. Once I verify there is an element I start to build on it. 

This might be of interest to look at:

```
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.senchalabs.gwt.gwtdriver.by.ByWidget;
import org.senchalabs.gwt.gwtdriver.by.FasterByChained;

public class BasicBindingTestInt extends BaseTest {

  @Test
  public void testComboExists() throws InterruptedException {
    gotoUrl("http://google.com"); // ignore google, it just tests the web driver loaded. Put your app url here. 

    // Given a content panel
    WebElement framedPanelElement = driver.findElement(new FasterByChained(By.xpath(".//*"), new ByWidget(driver,
        com.sencha.gxt.widget.core.client.ContentPanel.class)));

    // When looking for combo in panel 
    WebElement comboElement = framedPanelElement.findElement(new FasterByChained(By.xpath(".//*"), new ByWidget(driver,
        com.sencha.gxt.widget.core.client.form.ComboBox.class)));

    // Then the combo is not null
    Assert.assertNotNull(comboElement);
  }

}
```

```
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Rule;
import org.junit.rules.TestWatcher;
import org.junit.runner.Description;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Platform;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;

import com.sencha.gxt.test.it.rules.Retry;

public abstract class BaseTest {

  private static final Logger logger = Logger.getLogger(BaseTest.class.getName());

  private static WebDriver last;

  protected WebDriver driver;

  @Rule
  public TestWatcher quitFailedDriver = new TestWatcher() {
    @Override
    protected void failed(Throwable e, Description description) {
      last.quit();
      last = null;
      driver = null;
    }
  };

  @Rule
  public Retry retry = new Retry(3);

  @Before
  public void startBrowser() throws IOException, URISyntaxException {
    if (last != null) {
      driver = last;
      last = null;
      return;
    }

    String server = System.getProperty("webdriver.remote.server");

    if (server == null) {
      driver = createFireFoxDriver();
    } else {
      driver = createRemoteWebDriver();
    }

    driver.manage().timeouts().setScriptTimeout(5000, TimeUnit.MILLISECONDS);
  }

  @After
  public void stopBrowser() {
    try {
      // make sure there is no alert present, failing the test
      Assert.assertTrue("Alert found when trying to close browser",
          ExpectedConditions.not(ExpectedConditions.alertIsPresent()).apply(driver));
      last = driver;
    } catch (Exception ex) {
      driver.quit();
      last = null;
    }
  }

  public Dimension getBrowserWindowSize() {
    return driver.manage().window().getSize();
  }

  public Dimension setBrowserWindowPosition(Point targetPosition) {
    driver.manage().window().setPosition(targetPosition);
    return driver.manage().window().getSize();
  }

  public Dimension setBrowserWindowMaximized() {
    driver.manage().window().maximize();
    return driver.manage().window().getSize();
  }

  public void setBrowserWindowSize(Dimension targetSize) {
    driver.manage().window().setSize(targetSize);
  }

  protected void gotoUrl(String url) {
    logger.info("gotoEntrypoint() + url=" + url);
    driver.get(url);
  }

  private FirefoxDriver createFireFoxDriver() throws IOException, URISyntaxException {
    FirefoxProfile firefoxProfile = new FirefoxProfile();
    firefoxProfile.setPreference("browser.sessionstore.resume_from_crash", false);
    firefoxProfile.setPreference("app.update.auto", false);

    return new FirefoxDriver(firefoxProfile);
  }

  // TODO factor this up a step to a runner so that it can be run across many browsers
  private RemoteWebDriver createRemoteWebDriver() throws MalformedURLException {
    String server = System.getProperty("webdriver.remote.server");
    String browserRaw = System.getProperty("browser", "firefox");
    String platformRaw = System.getProperty("platform", Platform.getCurrent().name());

    DesiredCapabilities capabilities = new DesiredCapabilities(browserRaw, "",
        Enum.valueOf(Platform.class, platformRaw));

    return new RemoteWebDriver(new URL(server), capabilities);
  }

}
```

**Comment by branflake2267** [comment]
Oh I see you found a widget. cool. I'm late. If you get an element not found, usually that means the filter is too specific and you have to hone the query.

**Comment by PeterWippermann** [comment]
Good morning guys :-)
After I had to put this blocker aside for two days, I invested quite some time now to get things running and still I didn't make any progress :-(

This is my current status:
Your Sample App
- Running on my local Wildfly server
- AuthenticationTest is not working, because the module's name cannot be determined. That's strange since I'm able to run the same JavaScript manually in Firefox' Debugger console and there I can see the module name.

My application
- Detection of the module name is working fine here!
- However the ByNearestWidget never finds any elements
- I also tried @branflake2267 's test ( https://github.com/niloc132/gxt-driver/issues/10#issuecomment-151957285 ) against my app. Added a find statement to my VerticalLayoutContainer. Same error here.

GUI test Google
- Out of desperation I tried to run a test against google.de. But this didn't work also. I guess that's why I have to inherit TestableGXT right? ;-)

So what else can I do? Do you have any advice?
@niloc132 , you mentioned that compilation of class metadata could be disabled for me. You mean in the GWT compilation, don't you? How do I check that?

**Comment by PeterWippermann** [comment]
Ok, I was able to get the Sample app running. Of course, the mistake was on my side :-) Since I wanted to deploy the app on my existing AppServer, I built the war without any maven profile. Thus always the wrong module was built (Mail, not TestableMail). I changed this in the POM and now the AuthenticationTest runs fine against my AppServer.

I'm happy to see that my Firefox shouldn't be part of the problem I still have with my own app. So I will have to compare your app against mine now. Any ideas what might be different?

**Comment by branflake2267** [comment]
Nice job drilling the issue. Thanks for the feedback.

**Comment by branflake2267** [comment]
Not sure I understand the ideas that might be different?

**Comment by PeterWippermann** [comment]
I wanted to ask you, if you have any idea, what could the difference between the Sample app and my app - explaining why ByNearestWidget doesn't work for me :-)

**Comment by PeterWippermann** [comment]
Here's my own test code:

```
        WebElement textField = driver.findElement(By.id(USERNAME_INPUT));
        WebElement input = textField.findElement(By.tagName("input"));
        input.sendKeys(userName);

        // Working fine until here - with native Selenium means
        // The following three approaches to instantiate a model all fail with NoSuchElementException

        Field test = GwtWidget.find(Field.class, driver).withElement(textField).done();
        Field test2 = GwtWidget.find(Field.class, driver).withLabel("Username:").done();
        GwtWidget.find(Button.class, driver).withText("Login").done().click();
```

**Comment by branflake2267** [comment]
Hm, ByNearestWidget uses the current node, so I suspect the next query, the widget is not in the subtree of that current node. I'm not sure I could say much more without more context of how the HTML looks .

**Comment by PeterWippermann** [comment]
@branflake2267  @niloc132 Thanks for your help, I could solve my problem!
Indeed the gwt-maven-plugin was configured with: `<disableClassMetadata>true</disableClassMetadata>`

I had your advice in mind and found this by accident. Now it's all working as it should. Thank you very much! :-)
Issue can be closed from my side.

**Comment by branflake2267** [comment]
Cool. Nice job, thanks for the feedback.
